language: python
python:
    - "2.7"
    - "3.6"
    - "3.7"

install:
    - python setup.py install
    - pip install pytest pytest-cov coveralls

script:
    - py.test tests.py -v --cov trans --cov-report term-missing

after_success:
    - coveralls
